### ISSUE TITLE
ValueError: dict contains fields not in fieldnames: 'any_repository_has_fulltext'

### ISSUE THREAD

**Issue by yuch25** [ourresearch/openalex-documentation-scripts#1]
openalex-snapshot/data/works/updated_date=2023-04-05/part_000.gz
openalex-snapshot/data/works/updated_date=2023-04-06/part_000.gz
openalex-snapshot/data/works/updated_date=2023-04-07/part_000.gz
Traceback (most recent call last):
  File "/mnt/e/OpenAlex/openalex-snapshot-20230503/flatten-openalex-jsonl.py", line 684, in <module>
    flatten_works()
  File "/mnt/e/OpenAlex/openalex-snapshot-20230503/flatten-openalex-jsonl.py", line 652, in flatten_works
    open_access_writer.writerow(open_access)
  File "/home/yuc/anaconda3/lib/python3.10/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/home/yuc/anaconda3/lib/python3.10/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'any_repository_has_fulltext'

**Comment by J0nasW** [comment]
I also came across this issue. I added the 'any_repository_has_fulltext' field to the csv_files dict in line 187. This has solved the error.

```
'open_access': {
            'name': os.path.join(CSV_DIR, 'works_open_access.csv.gz'),
            'columns': [
                'work_id', 'is_oa', 'oa_status', 'oa_url', 'any_repository_has_fulltext'
            ]
        },
```

**Comment by caseydm** [comment]
This should be fixed. It was added in the latest update.
